Story1
LottieRugg/pubsOfSheffield pull request #3
Opened 2022-04-04 15:30 UTC by LottieRugg

Hello 
please let me know if you have any feedback!
Thank you

2022-04-04 15:53 UTC, ashleycoles requested changes
Really great work, a few comments here for ya!

2022-04-04 15:53 UTC, ashleycoles commented on functions.php
> +function connectToDatabase(){
You can actually return type hint this function as `: PDO` 

It should be formatted like this: `connectToDatabase(): PDO {`

2022-04-04 15:53 UTC, ashleycoles commented on functions.php
> +    $db = new PDO('mysql:host=db; dbname=pubs_of_sheffield', 'root', 'password');
Don't forget to set your default fetch mode to fetch assoc!

2022-04-04 15:53 UTC, ashleycoles commented on functions.php
> +    $returnItems = $db->prepare('SELECT `id`, `name`, `address`, `rating`, `picture`, `what_to_order`, `open_fire` FROM `pubs`;');
Suggest renaming this variable to query or something, just because this contains a query rather than the actual results

2022-04-04 15:53 UTC, ashleycoles commented on functions.php
> +    return $itemsList;
You could directly return the fetch all here (skipping setting it to a variable)

2022-04-04 15:53 UTC, ashleycoles commented on functions.php
> +function getAllItems($db){
You can return type hint this as array

2022-04-04 15:53 UTC, ashleycoles commented on functions.php
> +// Connect to the main database
This line should be part of the doc block (see your format for connectToDatabase)

2022-04-04 15:53 UTC, ashleycoles commented on pubs_of_sheffield.php
> +    } ?>
Suggest putting this into a function for displaying the pubs, this function could then be unit tested!

2022-04-04 15:53 UTC, ashleycoles commented on pubs_of_sheffield/db.opt
> +default-character-set=utf8mb4
Now that you have the .sql export you can delete this folder

2022-04-04 15:53 UTC, ashleycoles commented on pubs_of_sheffield.php
> +            <img src="<?php echo $item["picture"]; ?>" class="pub_image">
Don't forget to add some alt text to your images (could just use the name field)

2022-04-04 16:27 UTC, LottieRugg commented on functions.php
> +    $db = new PDO('mysql:host=db; dbname=pubs_of_sheffield', 'root', 'password');
I will, what happens if you don't tho? Seemed to be returning the right stuff

2022-04-05 10:15 UTC, ashleycoles requested changes

2022-04-05 10:15 UTC, ashleycoles commented on Tests/selectItem.php
> +class selectItem extends TestCase
I'd suggest renamign this class (and file) to be `selectItemTest` just to follow naming conventions

2022-04-05 10:15 UTC, ashleycoles commented on functions.php
> +function selectItem(array $itemsList): string
Missing docblock!

2022-04-05 10:18 UTC, LottieRugg commented on functions.php
> +function selectItem(array $itemsList): string
🤦‍♀️ doh!

2022-04-05 10:21 UTC, ashleycoles approved these changes

2022-04-05 10:21 UTC, merged